{{- if .Values.ingressClass.enabled -}}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ .Values.controller.ingressClass }}
  labels:
    {{- include "pangolin-ingress-controller.labels" . | nindent 4 }}
  annotations:
    ingressclass.kubernetes.io/is-default-class: {{ .Values.ingressClass.isDefault | quote }}
spec:
  controller: {{ .Values.ingressClass.controllerName }}
{{- end }}
