{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "pangolin-ingress-controller.fullname" . }}-leader-election
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pangolin-ingress-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "pangolin-ingress-controller.fullname" . }}-leader-election
subjects:
- kind: ServiceAccount
  name: {{ include "pangolin-ingress-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
