{{- if .Values.pangolin.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pangolin.apiKeySecretName }}
  namespace: {{ include "pangolin-ingress-controller.apiKeyNamespace" . }}
  labels:
    {{- include "pangolin-ingress-controller.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-key: {{ .Values.pangolin.apiKey | quote }}
{{- end }}
