apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pangolin-ingress-controller-leader-election
  namespace: pangolin-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pangolin-ingress-controller-leader-election
subjects:
- kind: ServiceAccount
  name: pangolin-ingress-controller
  namespace: pangolin-system
